# Generated by Django 4.2.3 on 2025-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='current_question_index',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Generating Questions'), (1, 'In Progress'), (2, 'Completed'), (3, 'Abandoned')], default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_limit_seconds',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status'], name='quizzes_qui_status_3ebe55_idx'),
        ),
    ]
